name: Build with GnuTLS
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt update && sudo apt install libgnutls28-dev nettle-dev
    - name: submodules
      run: git submodule update --init --recursive
    - name: cmake
      run: cmake -B build -DUSE_JUICE=1 -DUSE_GNUTLS=1
    - name: make
      run: (cd build; make -j2)
    - name: test
      run: ./build/tests
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: brew install gnutls nettle
    - name: submodules
      run: git submodule update --init --recursive
    - name: cmake
      run: cmake -B build -DUSE_JUICE=1 -DUSE_GNUTLS=1
    - name: make
      run: (cd build; make -j2)
    - name: test
      run: ./build/tests
