name: Build and test with OpenSSL
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: sudo apt update && sudo apt install libssl-dev
    - name: submodules
      run: git submodule update --init --recursive
    - name: cmake
      run: cmake -B build -DUSE_JUICE=1 -DUSE_GNUTLS=0
    - name: make
      run: (cd build; make)
    - name: test
      run: ./build/tests

